spring:
  # 选择加载不同环境的配置文件
  profiles:
    active: dev
  application:
    name: animalhome-back

---
#开发环境配置-dev
server:
  port: 18088
spring:
  profiles: dev
  cache:
    type: REDIS
  redis:
    #host: 10.159.137.117
    host: 127.0.0.1
    password: 772465redis
    port: 6379
    database: 1
    timeout: 5000ms
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mydb?useSSL=FALSE&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: songmin
    password: 123456
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.songmin.model